name: RSS-BRAND-BOT

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # Har 4 ghante baad refresh hoga taake band na ho

jobs:
  run-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Bot
        run: node index.js
